MODEL:
  TYPE: swin
  NAME: resnet50_COV_infection_fulltrained
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./pretrained_ckpt/resnet50_COV_infection_fulltrained.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
#    DEPTHS: [ 1, 1, 1, 1 ]
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7